name: base-orphans
version: 0.5.2
synopsis: Backwards-compatible orphan instances for base
license: MIT
author:
  - Simon Hengel <sol@typeful.net>
  - João Cristóvão <jmacristovao@gmail.com>
  - Ryan Scott <ryan.gl.scott@gmail.com>
maintainer:
  - Simon Hengel <sol@typeful.net>
  - João Cristóvão <jmacristovao@gmail.com>
  - Ryan Scott <ryan.gl.scott@gmail.com>
copyright:
  - (c) 2012-2016 Simon Hengel
  - (c) 2014-2016 João Cristóvão
  - (c) 2015-2016 Ryan Scott
category: Compatibility
description: >
  @base-orphans@ defines orphan instances that mimic instances available in
  later versions of @base@ to a wider (older) range of compilers.
  @base-orphans@ does not export anything except the orphan instances
  themselves and complements @<http://hackage.haskell.org/package/base-compat
  base-compat>@.

  See the README for what instances are covered:
  <https://github.com/haskell-compat/base-orphans#readme>.
  See also the
  <https://github.com/haskell-compat/base-orphans#what-is-not-covered what is not covered>
  section.

extra-source-files:
  - CHANGES.markdown
  - README.markdown

github: haskell-compat/base-orphans

ghc-options: -Wall

dependencies:
  - base >= 4.3 && < 5

library:
  source-dirs: src
  dependencies: ghc-prim
  exposed-modules: Data.Orphans
  other-modules: Data.Orphans.Prelude

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - base-orphans
      - hspec == 2.*
      - QuickCheck
