name: base-orphans
version: "0.8.3"
synopsis: Backwards-compatible orphan instances for base
license: MIT
author:
  - Simon Hengel <sol@typeful.net>
  - João Cristóvão <jmacristovao@gmail.com>
  - Ryan Scott <ryan.gl.scott@gmail.com>
maintainer:
  - Simon Hengel <sol@typeful.net>
  - João Cristóvão <jmacristovao@gmail.com>
  - Ryan Scott <ryan.gl.scott@gmail.com>
copyright:
  - (c) 2012-2017 Simon Hengel
  - (c) 2014-2017 João Cristóvão
  - (c) 2015-2017 Ryan Scott
category: Compatibility
description: |
  @base-orphans@ defines orphan instances that mimic instances available in
  later versions of @base@ to a wider (older) range of compilers.
  @base-orphans@ does not export anything except the orphan instances
  themselves and complements @<http://hackage.haskell.org/package/base-compat
  base-compat>@.

  See the README for what instances are covered:
  <https://github.com/haskell-compat/base-orphans#readme>.
  See also the
  <https://github.com/haskell-compat/base-orphans#what-is-not-covered what is not covered>
  section.
tested-with:   GHC == 7.0.4
             , GHC == 7.2.2
             , GHC == 7.4.2
             , GHC == 7.6.3
             , GHC == 7.8.4
             , GHC == 7.10.3
             , GHC == 8.0.2
             , GHC == 8.2.2
             , GHC == 8.4.4
             , GHC == 8.6.5
             , GHC == 8.8.3
             , GHC == 8.10.1

extra-source-files:
  - CHANGES.markdown
  - README.markdown

github: haskell-compat/base-orphans

ghc-options: -Wall

dependencies:
  - base >= 4.3 && < 5

library:
  source-dirs: src
  dependencies: ghc-prim
  exposed-modules: Data.Orphans
  other-modules: Data.Orphans.Prelude

tests:
  spec:
    defaults: sol/hpack-defaults@hspec-cabal-new
    dependencies:
      - base-orphans
      - QuickCheck
